### ISSUE TITLE
chater 10 animation don't work in Unity 2019

### ISSUE THREAD

**Issue by cocosistemas** [dr-matt-smith/Unity-2018-Cookbook-Third-Edition#1]
In Unity 2019 chapter 10 animation; mecanim project don't work. Character falls until his waist. I know that the book is for Unity 2018 but... it's possible to fix it? thx.

**Comment by dr-matt-smith** [comment]
Hi Diego,

I'm afraid I don't know Mechanim too well - the 3D animations and recipes were created by my previous co-author  Chico Queiroz
Unfortunately Chico hasn't worked on the Unity cookbooks for a few years. I was able to get it all working for 2018 since there were few changes from the previous version. However, I've no experience of 3D rigging in 2019 or the 2020 beta.

Here are some links I found about Mechanim in 2019, they might be useful:
Unity 2019 animation tutorials

https://gamedevacademy.org/unity-animator-tutorial/

https://blogs.unity3d.com/2019/05/14/introducing-the-animation-rigging-preview-package-for-unity-2019-1/

https://docs.unity3d.com/Manual/AnimationOverview.html

https://docs.unity3d.com/Packages/com.unity.animation.rigging@0.2/manual/index.html

https://docs.unity3d.com/Packages/com.unity.animation.rigging@0.2/manual/index.html


--
you might also try a free 10-day trial Packt subscription, to look at videos like this that might help:
https://www.packtpub.com/eu/game-development/game-design-unity-2019-video

--
you could also try ion the Unity forums, since if it is an issue between 2018 and 2019 others will have met it, and hopefully found solution s...


I'm currently working on an 2020 update for the book, but at present I've not got a section on Mechanim, since I'd have to find time to learn quite a bit, and already have 100s of pages to write.

I'm sorry I couldn't be more help - in the future, when I have some spare time, 3D modelling/rigging and video editing are skillsets I hope to pick up, but at present with my academic work, and books on Unity and PHP programming, and a family, I'm not able to keep up to date with all the features of a massing application such as Unity.

regards .. matt ..

On April 19, 2020 at 12:48 PM, Diego Jose Muñoz Carbajo <notifications@github.com> wrote:


In Unity 2019 chapter 10 animation; mecanim project don't work. Character falls until his waist. I know that the book is for Unity 2018 but... it's possible to fix it? thx.

**Comment by cocosistemas** [comment]
oh! well, close the issue and thanks
